create schema if not exists private;

create table if not exists public.guru (
  id text primary key,
  nama text not null,
  status text not null,
  tugas text not null,
  kategori text not null,
  jabatan text not null,
  image text,
  aktif boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  nama text,
  role text not null default 'guru' check (role in ('admin','guru')),
  guru_id text references public.guru(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  guru_id text not null references public.guru(id) on delete restrict,
  tanggal date not null default ((now() at time zone 'Asia/Jakarta')::date),
  waktu timestamptz not null default now(),
  status text not null check (status in ('hadir','izin','sakit','dinas')),
  keterangan text,
  created_by uuid not null default auth.uid() references auth.users(id) on delete restrict,
  updated_at timestamptz not null default now(),
  unique (guru_id, tanggal)
);

create index if not exists attendance_tanggal_idx on public.attendance(tanggal);
create index if not exists attendance_guru_tanggal_idx on public.attendance(guru_id, tanggal desc);
create index if not exists profiles_guru_id_idx on public.profiles(guru_id);
create index if not exists attendance_created_by_idx on public.attendance(created_by);

create or replace function private.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

create or replace function private.current_guru_id()
returns text
language sql
security definer
set search_path = public
as $$
  select guru_id from public.profiles where id = auth.uid();
$$;

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, nama)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'full_name', split_part(coalesce(new.email,''),'@',1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

revoke all on function private.is_admin() from public;
revoke all on function private.current_guru_id() from public;
revoke all on function private.handle_new_user() from public;
grant execute on function private.is_admin() to authenticated;
grant execute on function private.current_guru_id() to authenticated;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure private.handle_new_user();

alter table public.guru enable row level security;
alter table public.profiles enable row level security;
alter table public.attendance enable row level security;

drop policy if exists "guru_authenticated_read" on public.guru;
create policy "guru_authenticated_read" on public.guru for select to authenticated using (aktif = true);

drop policy if exists "profiles_self_read" on public.profiles;
drop policy if exists "profiles_admin_read" on public.profiles;
create policy "profiles_self_or_admin_read" on public.profiles for select to authenticated
using (id = (select auth.uid()) or (select private.is_admin()));


drop policy if exists "attendance_self_or_admin_read" on public.attendance;
create policy "attendance_self_or_admin_read" on public.attendance for select to authenticated using (private.is_admin() or guru_id = private.current_guru_id());

drop policy if exists "attendance_self_or_admin_insert" on public.attendance;
create policy "attendance_self_or_admin_insert" on public.attendance for insert to authenticated
with check (((select private.is_admin()) or guru_id = (select private.current_guru_id())) and created_by = (select auth.uid()));

drop policy if exists "attendance_self_or_admin_update" on public.attendance;
create policy "attendance_self_or_admin_update" on public.attendance for update to authenticated
using (private.is_admin() or guru_id = private.current_guru_id())
with check (private.is_admin() or guru_id = private.current_guru_id());

drop policy if exists "attendance_admin_delete" on public.attendance;
create policy "attendance_admin_delete" on public.attendance for delete to authenticated using (private.is_admin());

insert into public.guru (id,nama,status,tugas,kategori,jabatan,image) values
('dian-novita-handayani','Dian Novita Handayani','PNS','Pendidik','guru','Guru','images/guru-1.svg'),
('fitriana-tumanggor','Fitriana Tumanggor','PPPK Paruh Waktu','Guru Pendidikan Agama Islam (PAI)','mapel','Guru Pendidikan Agama Islam (PAI)','images/guru-2.svg'),
('lasminar-sianipar','Lasminar Sianipar','PPPK','Guru Kelas V','kelas','Guru Kelas V','images/guru-3.svg'),
('misriana','Misriana','PPPK','Koordinator P5; Guru Kelas I','kelas','Guru Kelas I / Koordinator P5','images/guru-4.svg'),
('nova-gustina-koto','Nova Gustina Koto, S.Pd. Gr','PPPK','Koordinator P5; Guru Kelas IV','kelas','Guru Kelas IV / Koordinator P5','images/guru-5.svg'),
('rennawaty-sinaga','Rennawaty Sinaga','PNS','Koordinator P5; Guru Kelas III','kelas','Guru Kelas III / Koordinator P5','images/guru-6.svg'),
('suriana-br-aruan','Suriana Br Aruan','PPPK','Bendahara BOS/BOP; Guru Kelas II','kelas','Guru Kelas II / Bendahara BOS/BOP','images/guru-1.svg'),
('syafaruddin','Syafaruddin','PNS','Guru PJOK','mapel','Guru PJOK','images/guru-2.svg'),
('zoelia-hartati','Zoelia Hartati','PPPK','Koordinator P5; Guru Kelas VI','kelas','Guru Kelas VI / Koordinator P5','images/guru-3.svg'),
('eliani','Eliani','PNS','Kepala Sekolah','pimpinan','Kepala Sekolah','images/kepala-sekolah.svg'),
('rahmad-fauzan','Rahmad Fauzan','PPPK Paruh Waktu','Tenaga Kependidikan','tendik','Tenaga Kependidikan','images/guru-6.svg')
on conflict (id) do update set nama=excluded.nama,status=excluded.status,tugas=excluded.tugas,kategori=excluded.kategori,jabatan=excluded.jabatan,image=excluded.image,aktif=true;